# coding: utf-8

"""
    User API

    A simple API to manage users  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        Get all users  # noqa: E501
        """
        pass

    def test_users_id_delete(self):
        """Test case for users_id_delete

        Delete a user by ID  # noqa: E501
        """
        pass

    def test_users_id_get(self):
        """Test case for users_id_get

        Get a user by ID  # noqa: E501
        """
        pass

    def test_users_id_put(self):
        """Test case for users_id_put

        Update a user by ID  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        Create a new user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
